//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.MemberInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMemberName;
		protected global::System.Web.UI.WebControls.TextBox txtPassword;
		protected global::System.Web.UI.WebControls.CheckBox chkSex;
		protected global::System.Web.UI.WebControls.TextBox txtLinkphoto;
		protected global::System.Web.UI.WebControls.TextBox txtEmail;
		protected global::System.Web.UI.WebControls.TextBox txtQQMSN;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
