//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.NewsInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtNewsTitle;
		protected global::System.Web.UI.WebControls.TextBox txtNewsKey;
		protected global::System.Web.UI.WebControls.TextBox txtWrite;
		protected global::System.Web.UI.WebControls.TextBox txtNewsTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtFatime;
		protected global::System.Web.UI.WebControls.TextBox txtImageURL;
		protected global::System.Web.UI.WebControls.TextBox txtHitNum;
		protected global::System.Web.UI.WebControls.TextBox txtNewsContent;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
