//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ComPany {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblCompanyID;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyNames;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyType;
		protected global::System.Web.UI.WebControls.TextBox txtComAddress;
		protected global::System.Web.UI.WebControls.TextBox txtComFax;
		protected global::System.Web.UI.WebControls.TextBox txtComPhoto;
		protected global::System.Web.UI.WebControls.TextBox txtComEmail;
		protected global::System.Web.UI.WebControls.TextBox txtQQ;
		protected global::System.Web.UI.WebControls.TextBox txtComwangzhi;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
