//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ComPany {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCompanyID;
	protected global::System.Web.UI.WebControls.Label lblCompanyNames;
	protected global::System.Web.UI.WebControls.Label lblCompanyType;
	protected global::System.Web.UI.WebControls.Label lblComAddress;
	protected global::System.Web.UI.WebControls.Label lblComFax;
	protected global::System.Web.UI.WebControls.Label lblComPhoto;
	protected global::System.Web.UI.WebControls.Label lblComEmail;
	protected global::System.Web.UI.WebControls.Label lblQQ;
	protected global::System.Web.UI.WebControls.Label lblComwangzhi;


       
    }
}
