//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Product {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblProID;
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtProTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtProXingID;
		protected global::System.Web.UI.WebControls.TextBox txtProchutime;
		protected global::System.Web.UI.WebControls.TextBox txtFatime;
		protected global::System.Web.UI.WebControls.CheckBox chkToujian;
		protected global::System.Web.UI.WebControls.TextBox txtHitNum;
		protected global::System.Web.UI.WebControls.TextBox txtProcontent;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
