//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.JobInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblJobID;
		protected global::System.Web.UI.WebControls.TextBox txtJobTitle;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtNunber;
		protected global::System.Web.UI.WebControls.TextBox txtStarttime;
		protected global::System.Web.UI.WebControls.TextBox txtDuxiang;
		protected global::System.Web.UI.WebControls.TextBox txtAge;
		protected global::System.Web.UI.WebControls.TextBox txtXueli;
		protected global::System.Web.UI.WebControls.TextBox txtMonery;
		protected global::System.Web.UI.WebControls.TextBox txtZhuanye;
		protected global::System.Web.UI.WebControls.TextBox txtEndtime;
		protected global::System.Web.UI.WebControls.TextBox txtMiaoshu;
		protected global::System.Web.UI.WebControls.TextBox txtLianxi;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
