//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.JobInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblJobID;
	protected global::System.Web.UI.WebControls.Label lblJobTitle;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblNunber;
	protected global::System.Web.UI.WebControls.Label lblStarttime;
	protected global::System.Web.UI.WebControls.Label lblDuxiang;
	protected global::System.Web.UI.WebControls.Label lblAge;
	protected global::System.Web.UI.WebControls.Label lblXueli;
	protected global::System.Web.UI.WebControls.Label lblMonery;
	protected global::System.Web.UI.WebControls.Label lblZhuanye;
	protected global::System.Web.UI.WebControls.Label lblEndtime;
	protected global::System.Web.UI.WebControls.Label lblMiaoshu;
	protected global::System.Web.UI.WebControls.Label lblLianxi;


       
    }
}
