//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.DingProduct {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtProXingID;
		protected global::System.Web.UI.WebControls.TextBox txtProTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtDingNum;
		protected global::System.Web.UI.WebControls.TextBox txtDingAddress;
		protected global::System.Web.UI.WebControls.TextBox txtLinkPhoto;
		protected global::System.Web.UI.WebControls.TextBox txtDingEmail;
		protected global::System.Web.UI.WebControls.CheckBox chkDingSex;
		protected global::System.Web.UI.WebControls.TextBox txtUsersName;
		protected global::System.Web.UI.WebControls.TextBox txtDingtime;
		protected global::System.Web.UI.WebControls.TextBox txtDingcontent;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
