//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.NicheInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblNicheID;
	protected global::System.Web.UI.WebControls.Label lblNicheTitle;
	protected global::System.Web.UI.WebControls.Label lblNicheKey;
	protected global::System.Web.UI.WebControls.Label lblFatime;
	protected global::System.Web.UI.WebControls.Label lblWrite;
	protected global::System.Web.UI.WebControls.Label lblImageURL;
	protected global::System.Web.UI.WebControls.Label lblNicheTypeID;
	protected global::System.Web.UI.WebControls.Label lblHitNum;
	protected global::System.Web.UI.WebControls.Label lblNicheContent;


       
    }
}
