//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.JiShuInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblJishuID;
		protected global::System.Web.UI.WebControls.TextBox txtJishuTitle;
		protected global::System.Web.UI.WebControls.TextBox txtJishuNum;
		protected global::System.Web.UI.WebControls.TextBox txtFatime;
		protected global::System.Web.UI.WebControls.TextBox txtjishuType;
		protected global::System.Web.UI.WebControls.TextBox txtImageURL;
		protected global::System.Web.UI.WebControls.TextBox txtJishuPath;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
