//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.JobZiJianInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblJobInfoID;
		protected global::System.Web.UI.WebControls.TextBox txtUsersname;
		protected global::System.Web.UI.WebControls.TextBox txtJobID;
		protected global::System.Web.UI.WebControls.CheckBox chkSex;
		protected global::System.Web.UI.WebControls.TextBox txtXueli;
		protected global::System.Web.UI.WebControls.TextBox txtJiguan;
		protected global::System.Web.UI.WebControls.TextBox txtBritday;
		protected global::System.Web.UI.WebControls.TextBox txtZhuanye;
		protected global::System.Web.UI.WebControls.TextBox txtJiaoyu;
		protected global::System.Web.UI.WebControls.TextBox txtJingyan;
		protected global::System.Web.UI.WebControls.TextBox txtPingjia;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
