//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.JobZiJianInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblJobInfoID;
	protected global::System.Web.UI.WebControls.Label lblUsersname;
	protected global::System.Web.UI.WebControls.Label lblJobID;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblXueli;
	protected global::System.Web.UI.WebControls.Label lblJiguan;
	protected global::System.Web.UI.WebControls.Label lblBritday;
	protected global::System.Web.UI.WebControls.Label lblZhuanye;
	protected global::System.Web.UI.WebControls.Label lblJiaoyu;
	protected global::System.Web.UI.WebControls.Label lblJingyan;
	protected global::System.Web.UI.WebControls.Label lblPingjia;


       
    }
}
